# Puerto en que escucha Spring Boot
server.port=8080

# Servicio de la base de datos (Adaptado a MariaDB y Docker)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://${DB_HOST:mariadb}:${DB_PORT:3306}/${DB_NAME:hogwarts_MMZ}
spring.datasource.username=${DB_USER:aaee_mmz}
spring.datasource.password=${DB_PASSWORD:root}

# Parámetros del Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2